output "env_local" {
  description = "Cloud Run/Firebase 連携用の環境変数 (make gen-env-local で自動生成可)"
  value       = <<-EOT
    # Generated by: make gen-env-local
    # Firestore
    GCP_PROJECT_ID=${data.terraform_remote_state.shared.outputs.project_id}
    FIRESTORE_DATABASE_ID=${data.terraform_remote_state.shared.outputs.firestore_database_name}
    # Firebase config (client SDK)
    NEXT_PUBLIC_FIREBASE_PROJECT_ID=${data.terraform_remote_state.shared.outputs.project_id}
    NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=${data.terraform_remote_state.shared.outputs.firebase_auth_domain}
    NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=${data.terraform_remote_state.shared.outputs.firebase_storage_bucket}
    NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=${data.terraform_remote_state.shared.outputs.firebase_messaging_sender_id}
    # 以下は Firebase コンソール > プロジェクトの設定 > マイアプリ > SDK の設定と構成 から取得
    NEXT_PUBLIC_FIREBASE_API_KEY=<ここに apiKey を貼り付け>
    NEXT_PUBLIC_FIREBASE_APP_ID=<ここに appId を貼り付け>
  EOT
}

output "service_url" {
  description = "Cloud Run service URL"
  value       = module.cloud_run.service_url
}

output "service_name" {
  description = "Cloud Run service name"
  value       = module.cloud_run.service_name
}

output "dns_cname_target" {
  description = "DNS CNAME target for custom domain"
  value       = module.cloud_run.dns_cname_target
}
